### ISSUE TITLE
ValueError: bytes is too large

### ISSUE THREAD

**Issue by mistycheney** [lebedov/msgpack-numpy#10]
When the array I am trying to pack is large, with shape (500, 500, 2620, 2), it fails.

==========================================================
/oasis/projects/nsf/csd181/yuncong/virtualenv-1.9.1/yuncongve/lib/python2.7/site-packages/msgpack_numpy.pyc in packb(o, default, **kwargs)
    141 
    142     kwargs['default'] = default
--> 143     return Packer(**kwargs).pack(o)
    144 
    145 def unpack(stream, object_hook=decode, **kwargs):

msgpack/_packer.pyx in msgpack._packer.Packer.pack (msgpack/_packer.cpp:223)()

msgpack/_packer.pyx in msgpack._packer.Packer.pack (msgpack/_packer.cpp:225)()

msgpack/_packer.pyx in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)()

msgpack/_packer.pyx in msgpack._packer.Packer._pack (msgpack/_packer.cpp:158)()

ValueError: bytes is too large

**Comment by lebedov** [comment]
The [msgpack spec](https://github.com/msgpack/msgpack/blob/master/spec.md) places limitations on the length of different data structures that can be serialized. If you are using double precision floats or 32 bit integers, your array will contain 500*500*2620*2*8 bytes when represented as a string - which is well beyond the 2**32-1 maximum.

**Comment by lebedov** [comment]
Out of curiosity, why are you serializing such a big array with msgpack? If you are doing so for storage on disk, a different format (e.g., hdf5) might be preferable.

**Comment by mistycheney** [comment]
Oh, I overlooked the string length limit. Yes, I want to dump the data to disk. I guess I will try hdf5 instead. Thanks.
