### ISSUE TITLE
Can't open files created in 0.3.6 using latest code

### ISSUE THREAD

**Issue by craffel** [lebedov/msgpack-numpy#12]
Hi, thanks for this useful library.  After this commit:
https://github.com/lebedov/msgpack-numpy/commit/be01578967e0ee14dabf4db4bec03c2195b924f0
I can't open files created prior to it, in Python 2.7.11.  I get a `UnicodeDecodeError`, e.g. 
`UnicodeDecodeError: 'utf8' codec can't decode byte 0x9b in position 0: invalid start byte`
If you are aware that it's not backwards-compatible, no worries and feel free to close.  But, it would be great if it was!

**Comment by lebedov** [comment]
You should still be able to decode data that was encoded with earlier revisions if you set ``encoding=None`` when calling ``load`` or ``loads``.
