### ISSUE TITLE
Wire-incompatibility between 0.3.7. and 0.3.9

### ISSUE THREAD

**Issue by hmeine** [lebedov/msgpack-numpy#17]
Although there was only a minor version increase, we have problems with passing ndarrays between (marshalling) processes running 0.3.7 and (demarshalling) processes running 0.3.9.

Was that intended?  It's kind of evil, because one side is a pre-packaged environment, and that's now incompatible with the default that's pip installed. :-(

**Comment by lebedov** [comment]
Probably not, but your point that wire compatibility should be maintained within major versions is well-taken. I'll make a note of the incompatibility between versions in the change log. Sorry about the breakage.
