### ISSUE TITLE
Compatibily issue introduced by issue #15

### ISSUE THREAD

**Issue by proximous** [lebedov/msgpack-numpy#20]
Issue #15 added a "kind" field.  This breaks compatibility with data encoded with older versions.

I'm not an expert, but is seems that simply testing for "kind" before trying to access it would resolve this compatibility (at least it does for me).

Specifically, if line #76 is changed from:
`if obj[b'kind'] == b'V':`

to 

`if b'kind' in obj and obj[b'kind'] == b'V'`

then I can successfully read my old files. If this is the correct fix, could you please implement and update to pypi?  Thanks.

**Comment by lebedov** [comment]
Done.
