### ISSUE TITLE
AttributeError: module 'msgpack._unpacker' has no attribute 'unpack'

### ISSUE THREAD

**Issue by nikhil8786** [lebedov/msgpack-numpy#26]
Hi,
I am facing this problem while running my code:
AttributeError: module 'msgpack._unpacker' has no attribute 'unpack'
Python Version : 3.6
Os : Ubuntu 14.04
msgpack-numpy Version: 0.4.2
msgpack : 0.5.5
numpy : 1.14.0

**Comment by bk201** [comment]
Hi,

See same issue today.
Seems unpack() function is removed from unpacker in recent commit.

https://github.com/msgpack/msgpack-python/commit/da902f9c1d996fb461f1efef6487ef40d32d365a

**Comment by danielhauagge** [comment]
Running into the same issue

**Comment by lebedov** [comment]
Updated to import from main package namespace in latest release.
