### ISSUE TITLE
Getting DeprecationWarning on decode function.

### ISSUE THREAD

**Issue by ardzoht** [lebedov/msgpack-numpy#27]
Using the decode function on message objects, I'm getting the following message constantly...

> DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  dtype=np.dtype(descr)).reshape(obj[b'shape'])

Should it use frombuffer function from now on?

**Comment by lebedov** [comment]
Sure - updated.
