### ISSUE TITLE
Loading numpy array outside of Python

### ISSUE THREAD

**Issue by fonaro** [lebedov/msgpack-numpy#28]
How will other (non python) implementation of msgpack handles this?
For example, what should I use when parsing msgpack via C++?
https://github.com/msgpack/msgpack-c

**Comment by lebedov** [comment]
msgpack_numpy effectively serializes a dict containing the shape, contents (as raw bytes), and data type of a numpy object. For non-Python msgpack implementations, one would need to write a decoder that deserializes each of those pieces of information and uses them to instantiate and set a suitable data structure for whatever language was used for that implementation (e.g., an [Eigen](http://eigen.tuxfamily.org/) array for C++). I haven't investigated whether there are existing C++ msgpack decoders that can unpack encoded Python dicts, though.
