### ISSUE TITLE
Add python3 classifier to setup.py

### ISSUE THREAD

**Issue by pklapperich** [lebedov/msgpack-numpy#29]
By listing only the "Python" classifier in setup.py, this project is advertising lack of support for Python3 and causes it to show up on projects like [py3readiness](https://hugovk.github.io/py3readiness/) (which attempts to track the porting effort to Python3 in advance of Python2 EOL).

I think this project is properly classified by:
```
    'Programming Language :: Python',
    'Programming Language :: Python :: 2.7',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.4',
    'Programming Language :: Python :: 3.5',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
```

**Comment by lebedov** [comment]
Good point - done.
