### ISSUE TITLE
I made a javascript library that read the same msgpack files

### ISSUE THREAD

**Issue by redhog** [lebedov/msgpack-numpy#53]
Heays! I've written a javascript library that is able to decode and encode javascript TypedArrays the same way this library encodes numpy arrays, meaning that a server side python app can communicate with a client side javascript app and include array data. Would you be interested in linking to this library from your README?

https://github.com/emerald-geomodelling/msgpack-numpy-js

**Comment by lebedov** [comment]
Sure - done!
