### ISSUE TITLE
Rust version: msgpack-numpy-rs 

### ISSUE THREAD

**Issue by terencezl** [lebedov/msgpack-numpy#55]
Hello,

I’ve long been a user of this package. It serves the targeted audience well when they need to serialize arrays in a well-supported format, and performance is quite good.

Lately the Rust ecosystem is growing fast, and I was doing some processing on that side for improved performance. I ended up singling it out to be a full package: https://github.com/clearviewai/msgpack-numpy-rs and released it as an open-source project under my company’s OSS initiative. It strives for full compatibility with your package, with some known exceptions outlined. It has a good number of tests for cross-language scenarios.

Would it be something worthwhile to add on the README here?

Best,
Terence

**Comment by lebedov** [comment]
Sure - done!
