### ISSUE TITLE
msgpack._packer issue

### ISSUE THREAD

**Issue by mehdisadeghi** [lebedov/msgpack-numpy#9]
This is similar to issue #6.

`_packer` is an internal variable of msgpack and if cython is not available when installing msgpack, then it would not be available as well. In this case msgpack will fallback to pure python installation and will not compile its cython extensions.

Does msgpack_numpy explicitly requires those cython extensions to function properly? If yes, then it is a good idea to mention it in documents to inform users about it.

**Comment by lebedov** [comment]
Good point - I updated the package to fall back to the pure Python implementation when the extension is unavailable (or when the MSGPACK_PUREPYTHON env variable is set). Also made a note of this in the README.
